// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iziuwznumqoirxaywcwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6aXV3em51bXFvaXJ4YXl3Y3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMjkyNjMsImV4cCI6MjA2MTkwNTI2M30.U1ukmQoEimj_mD5HvzjlxZRh8UxsIwf_KXDpOUREzkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);